# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
